name: CI - Test & Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AZURE_STORAGE_ACCOUNT: qaplaywrightstorage

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Node.js for Playwright
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Playwright tests
        working-directory: ./playwright-api-terraform-demo/playwright-tests
        run: |
          npm install
          npx playwright install
          npx playwright test --reporter=html
          mkdir -p ../../reports/ui
          mv ../reports/ui-report/* ../../reports/ui/

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run API tests with pytest
        working-directory: ./playwright-api-terraform-demo/api-tests/python
        run: |
          pip install -r requirements.txt
          pytest --html=../../reports/api/index.html --self-contained-html

      - name: Create landing page with links to reports
        run: |
          mkdir -p reports
          echo '<html><body><h1>Test Reports</h1><ul>' > reports/index.html
          echo '<li><a href="ui/index.html">UI Test Report (Playwright)</a></li>' >> reports/index.html
          echo '<li><a href="api/index.html">API Test Report (Pytest)</a></li>' >> reports/index.html
          echo '</ul></body></html>' >> reports/index.html

      - name: Upload Reports to Azure Blob Static Site
        run: |
          az storage blob upload-batch \
            --account-name $AZURE_STORAGE_ACCOUNT \
            --destination \$web \
            --source reports \
            --overwrite
