name: CI - Test & Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AZURE_STORAGE_ACCOUNT: qaplaywrightstorage

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Node.js for Playwright
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm dependencies at repo root
        run: npm install || echo "No package.json in root, skipping"

      - name: Run Playwright tests
        working-directory: ./playwright-tests
        run: |
          npx playwright install
          npx playwright test --reporter=html
          mkdir -p ../../reports/ui
          if [ -d "../playwright-report" ]; then
            cp -r ../playwright-report/* ../../reports/ui/
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run API tests with pytest
        working-directory: ./api-tests/python
        run: |
          pip install -r requirements.txt
          mkdir -p ../../reports/api
          pytest --html=../../reports/api/index.html --self-contained-html

      - name: Create unified single HTML report
        run: |
          mkdir -p reports

          PYTEST_HTML=$(base64 -w 0 reports/api/index.html)
          PLAYWRIGHT_HTML=$(base64 -w 0 reports/ui/index.html)

          cat > reports/index.html <<EOF
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <title>Combined Test Reports</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 20px; }
              h1 { font-size: 24px; }
              h2 { font-size: 20px; margin-top: 40px; }
              iframe { width: 100%; height: 600px; border: 1px solid #ccc; margin-top: 10px; }
            </style>
          </head>
          <body>
            <h1>Combined Test Reports</h1>

            <h2>UI Test Report (Playwright)</h2>
            <iframe srcdoc="\$(echo $PLAYWRIGHT_HTML | base64 --decode)" sandbox></iframe>

            <h2>API Test Report (Pytest)</h2>
            <iframe srcdoc="\$(echo $PYTEST_HTML | base64 --decode)" sandbox></iframe>
          </body>
          </html>
          EOF

      - name: Upload Single Report to Azure Blob Static Site
        run: |
          az storage blob upload \
            --account-name $AZURE_STORAGE_ACCOUNT \
            --container-name \$web \
            --file reports/index.html \
            --name index.html \
            --overwrite
